# Generated by Django 4.0.4 on 2022-05-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_task_completed_task_stage_task_timer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='stage',
            field=models.CharField(default='To Do', max_length=10, null=True),
        ),
    ]
