# Generated by Django 4.0.4 on 2022-05-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='timerState',
            field=models.BooleanField(default=False),
        ),
    ]
