# Generated by Django 4.0.4 on 2022-05-04 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_timerstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='stage',
            field=models.CharField(default='ToDo', max_length=10, null=True),
        ),
    ]
